/**
 * Константы ошибок для промокодов
 */
export const PROMO_CODE_ERRORS = {
    NOT_ACTIVE: 'PROMO_CODE_NOT_ACTIVE',
    LIMIT_EXCEEDED: 'PROMO_CODE_LIMIT_EXCEEDED',
    USER_LIMIT_EXCEEDED: 'PROMO_CODE_USER_LIMIT_EXCEEDED',
    NOT_STARTED: 'PROMO_CODE_NOT_STARTED',
    EXPIRED: 'PROMO_CODE_EXPIRED',
    NOT_FOUND: 'PROMO_CODE_NOT_FOUND',
} as const;
